//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rename.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rename_Helpers_Commands_pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rename_Helpers_Commands_pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rename.Helpers.Rename.Helpers.Commands.pl", typeof(Rename_Helpers_Commands_pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaje katalogi do listy przetwarzanych. Użycie: Add &lt;kat1&gt; [&lt;kat2&gt;] [...].
        /// </summary>
        internal static string DirectorySelector_AddHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_AddHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powoduje wyłączenie wyświetlania informacji w konsoli. Użycie: BeSilent.
        /// </summary>
        internal static string DirectorySelector_BeSilentHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_BeSilentHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czyści listę katalogów do przetworzenia. Użycie: Clear.
        /// </summary>
        internal static string DirectorySelector_ClearHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_ClearHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czyści ekran konsoli. Użycie: ClearScreen.
        /// </summary>
        internal static string DirectorySelector_ClearScreenHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_ClearScreenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kończy etap wyboru katalogów. Użycie: Complete.
        /// </summary>
        internal static string DirectorySelector_CompleteHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_CompleteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powoduje włączenie wyświetlania rezultatów w konsoli. Użycie: DontBeSilent.
        /// </summary>
        internal static string DirectorySelector_DontBeSilentHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_DontBeSilentHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetla listę poleceń oraz ich użycie lub pomoc dla wybrancyh komend. Usage: Help [&lt;cmd1&gt;] [&lt;cmd2&gt;] [...].
        /// </summary>
        internal static string DirectorySelector_HelpHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_HelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetla listę katalogów do przetworzenia. Użycie: List.
        /// </summary>
        internal static string DirectorySelector_ListHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_ListHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwa katalogi z listy. Użycie: Remove &lt;kat1&gt; [&lt;kat2&gt;] [...].
        /// </summary>
        internal static string DirectorySelector_RemoveHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_RemoveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalogi zostały dodane do listy..
        /// </summary>
        internal static string Messages_Directories_added {
            get {
                return ResourceManager.GetString("Messages.Directories_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Katalogi zostały usunięte z listy..
        /// </summary>
        internal static string Messages_Directories_removed {
            get {
                return ResourceManager.GetString("Messages.Directories_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista katalogów opróżniona..
        /// </summary>
        internal static string Messages_Directory_list_cleared {
            get {
                return ResourceManager.GetString("Messages.Directory_list_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Właściwośc {0} już znajduje się na liście przez co nie została dodana..
        /// </summary>
        internal static string PropertySelector__0__is_already_on_the_list {
            get {
                return ResourceManager.GetString("PropertySelector__0__is_already_on_the_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaje właściwości do listy. Użycie: Add &lt;w1&gt; [&lt;w2&gt;] [...].
        /// </summary>
        internal static string PropertySelector_AddHelp {
            get {
                return ResourceManager.GetString("PropertySelector_AddHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne właściwości:.
        /// </summary>
        internal static string PropertySelector_Available_Properties {
            get {
                return ResourceManager.GetString("PropertySelector_Available_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opróżnia listę właściwiości. Użycie: Clear.
        /// </summary>
        internal static string PropertySelector_ClearHelp {
            get {
                return ResourceManager.GetString("PropertySelector_ClearHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czyści okno konsoli. Użycie: ClearScreen.
        /// </summary>
        internal static string PropertySelector_ClearScreenHelp {
            get {
                return ResourceManager.GetString("PropertySelector_ClearScreenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ krok wyboru właściwości. Użycie: Complete.
        /// </summary>
        internal static string PropertySelector_CompleteHelp {
            get {
                return ResourceManager.GetString("PropertySelector_CompleteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetla listę poleceń. Użycie: HelpCommands.
        /// </summary>
        internal static string PropertySelector_HelpCommandsHelp {
            get {
                return ResourceManager.GetString("PropertySelector_HelpCommandsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetla listę poleceń wraz z pomocą i dostępnymi właściwościami. Użycie: Help [&lt;cmd1&gt;] [&lt;cmd2&gt;] [...].
        /// </summary>
        internal static string PropertySelector_HelpHelp {
            get {
                return ResourceManager.GetString("PropertySelector_HelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetla listę dostępnych właściwości. Użycie: HelpProperties.
        /// </summary>
        internal static string PropertySelector_HelpPropertiesHelp {
            get {
                return ResourceManager.GetString("PropertySelector_HelpPropertiesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetla listę wybranych właściwości. Użycie: List.
        /// </summary>
        internal static string PropertySelector_ListHelp {
            get {
                return ResourceManager.GetString("PropertySelector_ListHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Właściwości zostały dodane do listy..
        /// </summary>
        internal static string PropertySelector_Properties_added {
            get {
                return ResourceManager.GetString("PropertySelector_Properties_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Właściwości zostały usunięte z listy..
        /// </summary>
        internal static string PropertySelector_Properties_removed {
            get {
                return ResourceManager.GetString("PropertySelector_Properties_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista właściwości opróżniona..
        /// </summary>
        internal static string PropertySelector_Property_list_cleared {
            get {
                return ResourceManager.GetString("PropertySelector_Property_list_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwa właściwości z listy. Użycie: Remove &lt;p1&gt; [&lt;p2&gt;] [...].
        /// </summary>
        internal static string PropertySelector_RemoveHelp {
            get {
                return ResourceManager.GetString("PropertySelector_RemoveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybrane właściwości:.
        /// </summary>
        internal static string PropertySelector_Selected_Properties {
            get {
                return ResourceManager.GetString("PropertySelector_Selected_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy plik pominięć: {0}.
        /// </summary>
        internal static string SkipFile_New_skip_file_format {
            get {
                return ResourceManager.GetString("SkipFile_New_skip_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprzedni plik pominięć: {0}.
        /// </summary>
        internal static string SkipFile_Old_skip_file_format {
            get {
                return ResourceManager.GetString("SkipFile_Old_skip_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj ścieżkę do pliku pominięć lub wciśnij Enter aby użyć domyślnej:.
        /// </summary>
        internal static string SkipFile_Prompt_Enter_the_skip_file {
            get {
                return ResourceManager.GetString("SkipFile_Prompt_Enter_the_skip_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wciśnij Enter aby potwierdzić lub wprowadź inną ścieżkę:.
        /// </summary>
        internal static string SkipFile_Prompt_Press_Enter_once_more {
            get {
                return ResourceManager.GetString("SkipFile_Prompt_Press_Enter_once_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozwala wybrać jakiego pliku użyć do pomijania określonych słów. Zauważ: Jeśli więcej niż jedna ścieżka jest wprowadzona, użyta będzie tylko pierwsza. Użycie: Select &lt;sciezka&gt;.
        /// </summary>
        internal static string SkipFile_SelectHelp {
            get {
                return ResourceManager.GetString("SkipFile_SelectHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Wpisz &apos;Help&apos; aby uzyskać pomoc:.
        /// </summary>
        internal static string Type_Help_for_help {
            get {
                return ResourceManager.GetString("Type_Help_for_help", resourceCulture);
            }
        }
    }
}
