//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rename.Helpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rename_Helpers_Commands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rename_Helpers_Commands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rename.Helpers.Rename.Helpers.Commands", typeof(Rename_Helpers_Commands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add directories to processing list. Usage: Add &lt;dir1&gt; [&lt;dir2&gt;] [...].
        /// </summary>
        internal static string DirectorySelector_AddHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_AddHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes Console output to be disabled. Usage: BeSilent.
        /// </summary>
        internal static string DirectorySelector_BeSilentHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_BeSilentHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list of directories to process. Usage: Clear.
        /// </summary>
        internal static string DirectorySelector_ClearHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_ClearHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear current console&apos;s screen. Usage: ClearScreen.
        /// </summary>
        internal static string DirectorySelector_ClearScreenHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_ClearScreenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete directory selection step. Usage: Complete.
        /// </summary>
        internal static string DirectorySelector_CompleteHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_CompleteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes Console output to be enabled. Usage: DontBeSilent.
        /// </summary>
        internal static string DirectorySelector_DontBeSilentHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_DontBeSilentHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list of Commands and their usage or chosen commands&apos; help. Usage: Help [&lt;cmd1&gt;] [&lt;cmd2&gt;] [...].
        /// </summary>
        internal static string DirectorySelector_HelpHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_HelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list of directories to process. Usage: List.
        /// </summary>
        internal static string DirectorySelector_ListHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_ListHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove directories from the list. Usage: Remove &lt;dir1&gt; [&lt;dir2&gt;] [...].
        /// </summary>
        internal static string DirectorySelector_RemoveHelp {
            get {
                return ResourceManager.GetString("DirectorySelector_RemoveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories added to list..
        /// </summary>
        internal static string Messages_Directories_added {
            get {
                return ResourceManager.GetString("Messages.Directories_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories removed from the list..
        /// </summary>
        internal static string Messages_Directories_removed {
            get {
                return ResourceManager.GetString("Messages.Directories_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory list cleared..
        /// </summary>
        internal static string Messages_Directory_list_cleared {
            get {
                return ResourceManager.GetString("Messages.Directory_list_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already on the list so it wasn&apos;t added..
        /// </summary>
        internal static string PropertySelector__0__is_already_on_the_list {
            get {
                return ResourceManager.GetString("PropertySelector__0__is_already_on_the_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add properties to list. Usage: Add &lt;p1&gt; [&lt;p2&gt;] [...].
        /// </summary>
        internal static string PropertySelector_AddHelp {
            get {
                return ResourceManager.GetString("PropertySelector_AddHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Properties:.
        /// </summary>
        internal static string PropertySelector_Available_Properties {
            get {
                return ResourceManager.GetString("PropertySelector_Available_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear properties list. Usage: Clear.
        /// </summary>
        internal static string PropertySelector_ClearHelp {
            get {
                return ResourceManager.GetString("PropertySelector_ClearHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear current console&apos;s screen. Usage: ClearScreen.
        /// </summary>
        internal static string PropertySelector_ClearScreenHelp {
            get {
                return ResourceManager.GetString("PropertySelector_ClearScreenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete property selection step. Usage: Complete.
        /// </summary>
        internal static string PropertySelector_CompleteHelp {
            get {
                return ResourceManager.GetString("PropertySelector_CompleteHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list of commands. Usage: HelpCommands.
        /// </summary>
        internal static string PropertySelector_HelpCommandsHelp {
            get {
                return ResourceManager.GetString("PropertySelector_HelpCommandsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list of commands with their help and available properties. Usage: Help [&lt;cmd1&gt;] [&lt;cmd2&gt;] [...].
        /// </summary>
        internal static string PropertySelector_HelpHelp {
            get {
                return ResourceManager.GetString("PropertySelector_HelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list of available properties. Usage: HelpProperties.
        /// </summary>
        internal static string PropertySelector_HelpPropertiesHelp {
            get {
                return ResourceManager.GetString("PropertySelector_HelpPropertiesHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display list of selected properties. Usage: List.
        /// </summary>
        internal static string PropertySelector_ListHelp {
            get {
                return ResourceManager.GetString("PropertySelector_ListHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties added to list..
        /// </summary>
        internal static string PropertySelector_Properties_added {
            get {
                return ResourceManager.GetString("PropertySelector_Properties_added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties removed from the list..
        /// </summary>
        internal static string PropertySelector_Properties_removed {
            get {
                return ResourceManager.GetString("PropertySelector_Properties_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property list cleared..
        /// </summary>
        internal static string PropertySelector_Property_list_cleared {
            get {
                return ResourceManager.GetString("PropertySelector_Property_list_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove properties from the list. Usage: Remove &lt;p1&gt; [&lt;p2&gt;] [...].
        /// </summary>
        internal static string PropertySelector_RemoveHelp {
            get {
                return ResourceManager.GetString("PropertySelector_RemoveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Properties:.
        /// </summary>
        internal static string PropertySelector_Selected_Properties {
            get {
                return ResourceManager.GetString("PropertySelector_Selected_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New skip file: {0}.
        /// </summary>
        internal static string SkipFile_New_skip_file_format {
            get {
                return ResourceManager.GetString("SkipFile_New_skip_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old skip file: {0}.
        /// </summary>
        internal static string SkipFile_Old_skip_file_format {
            get {
                return ResourceManager.GetString("SkipFile_Old_skip_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the skip file path to use or press Enter to use the default:.
        /// </summary>
        internal static string SkipFile_Prompt_Enter_the_skip_file {
            get {
                return ResourceManager.GetString("SkipFile_Prompt_Enter_the_skip_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter once more to confirm or enter different path:.
        /// </summary>
        internal static string SkipFile_Prompt_Press_Enter_once_more {
            get {
                return ResourceManager.GetString("SkipFile_Prompt_Press_Enter_once_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which file to use for skipping certain words. Note: If more than one path is entered, only the first one will be used. Usage: Select &lt;path&gt;.
        /// </summary>
        internal static string SkipFile_SelectHelp {
            get {
                return ResourceManager.GetString("SkipFile_SelectHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Type &apos;Help&apos; for help:.
        /// </summary>
        internal static string Type_Help_for_help {
            get {
                return ResourceManager.GetString("Type_Help_for_help", resourceCulture);
            }
        }
    }
}
